version: "3.1"
services:
  rust-dev:
    container_name: rust-dev
    build:
      context: .
    restart: "unless-stopped"
    network_mode: "host"
    privileged: true
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
